#------------------------------------------------------------------------------#
# 0. Introduction and Goals ----------------------------------------------------
{
  # This is the Iterator_Parameter_Dependents.R script.

  # The goal of this script is do define the higher-level functions in the 
  # Robusntess_Iterator.R script that need to know the user defined iterator 
  # parameters to function (see Iterator_Params.R). 

  # Of all the functions defined in this project, only  the functions below need
  # to be passed the iterator parameters in order to execute, and these 
  # functions are only called in the Robustness_Iterator.R and the 
  # Iterator_Params.R script. There is one function, summarise_Metadata, that 
  # both uses formals(fun) for iterator_parameters and also sets iterator 
  # parameters. As such, summarise_Metadata() could go in this script or the 
  # Iterator_Params.R script, but it's been saved in Iterator_Params.R.

  # The reason the functions below need to know the iterator parameters is to 
  # accurately name and describe the results produced by the iterator, whether
  # this be naming a save file or giving a plot description. 

  # Please read the documentation of the iterator and iterator parameters before
  # diving into this script.
  
}



#------------------------------------------------------------------------------#
# 1. Defining Functions---------------------------------------------------------

calculate_Runtime <- function(runtime) {
  
  # save the names of the time-points for later
  runtime_labels <- names(runtime)
  
  # convert run time to numeric so we can perform arithmetic operations on
  # them. In this case we need it for subtractions, to calculate the duration
  # between checkpoints
  runtime_numeric <- as.numeric(runtime)
  
  # We calculate the passage of time between checkpoints in the 
  # resource_Robustness().
  # Step duration is the duration of a step between neighboring checkpoints.
  # Time elapsed is the duration between the completion of a step and the 
  # start of the script.
  
  step_duration <- c(0) # No time has passed when the script is initialized.
  time_elapsed  <- c(0) # No time has passed when the script is initialized.
  
  # starting with the second index of runtime_numeric until the last index
  for (i in 2:length(runtime_numeric)) {
    
    # subtract the preceding checkpoint from the checkpoint at i, this is the 
    # amount of time that passed between these two checkpoints
    step_duration <- c(step_duration, 
                       runtime_numeric[[i]] - runtime_numeric[[i-1]])
    
    # subtract the very first checkpoint from the checkpoint at i, this is all
    # the time that has elapsed up until now.
    time_elapsed  <- c(time_elapsed,
                       runtime_numeric[[i]] - runtime_numeric[[1]])
    
  }
  
  # Turn seconds into time periods using lubridate and round for simplicity
  # Time periods are HH:MM:SS, which is earier to understand than just values
  # in seconds.
  step_duration <- round(seconds_to_period(step_duration))
  time_elapsed  <- round(seconds_to_period(time_elapsed))
  
  
  # summarize all the runtime data in a tibble
  runtime <- runtime               %>%
    as_tibble_col()                %>%
    unnest(cols = c(value))        %>%
    rename("Start Time" = "value") %>% 
    add_column("Step Name"      = runtime_labels, .before = 1) %>%
    add_column("Step Duration"  = step_duration) %>%
    add_column("Time Elapsed"   = time_elapsed) 
  
  
  # Get rid of clutter in the environment
  rm(runtime_numeric, 
     step_duration, 
     time_elapsed, 
     runtime_labels,
     i)
  
  return(runtime)
}

# summarise_Metadata()
{
  #' Summarizes the metadate relevant for the Robustness Iterator
  #' 
  #' @description This function summarizes all the iterator parameters and used
  #' file names into one metadata object.
  #' 
  #' @param runtime The output of the calculate_Runtime() function, showing
  #' the time spent on various steps in resource_Robustness.
  #' 
  #' @param time_of_run What time was this script run at? Used as an argument 
  #' for auto_file_Name() to generate the same file names that were used 
  #' earlier. Also stored in the metadata object. Should always be passed the 
  #' char tag generated by create_Params().
  #' 
  #' @param dilution_params What arguments were used in dilution robustness?
  #' Should always be passed formals(wrap_resource_Robustness()).
  #' 
  #' @param testdata_type What type of testdata was used in the iterator? Should
  #' always be passed formals(extract_Testdata)$testdata_type.
  #' 
  #' @param master_seed_list What master_seed_list was the iterator run with?
  #' Should always be passed the seed list output from create_Params().
  #' 
  #' @param save_results Should the results from the iterator be saved 
  #' (including plots)? The save_Results() function will later refer to this.
  #' This value is also stored in the metadata. Only takes a boolean as a
  #' default, not a vector of a boolean.
  #' 
  #' @param trial_run Is this a trial run of the iterator or serious results?
  #' Takes a boolean. If this is a trial run, the save file names, logs and plot
  #' captions will reflect this. Only takes a boolean as a default, not a vector
  #' of a boolean.
  #' 
  #' @return Returns a list of metadata and parameters.
  
  
  
  summarise_Metadata <- function(number_seeds,
                                 master_seed_list,
                                 testdata_type,
                                 feature_type, 
                                 preserve_topology,    
                                 dilution_props,
                                 number_ranks,
                                 methods_vector,
                                 
                                 sink_output,    
                                 liana_warnings,
                                 
                                 cellchat_nperms,       
                                 bundled_outputs,
                                 master_outputs,
                                 
                                 
                                 save_results,
                                 trial_run,
                                 
                                 runtime,
                                 time_of_run) {
    
    # Summarize the metadata parameters
    meta_params <- list(
      "time_of_run"  = time_of_run,
      "save_results" = save_results,
      "trial_run"    = trial_run
    )
    
    dilution_params <- list(
      "number_seeds"      = number_seeds,
      "master_seed_list"  = master_seed_list,
      "testdata_type"     = testdata_type,
      "feature_type"      = feature_type, 
      "preserve_topology" = preserve_topology,    
      "dilution_props"    = dilution_props,
      "number_ranks"      = number_ranks ,
      "methods_vector"    = methods_vector,
      
      "sink_output"       = sink_output,    
      "liana_warnings"    = liana_warnings,
      
      "cellchat_nperms"   = cellchat_nperms,       
      "bundled_outputs"   = bundled_outputs,
      "master_outputs"    = master_outputs
    )
    
    # Put all the parameters in a list
    metadata <- list(
      "runtime"         = runtime,
      "dilution_params" = dilution_params,
      "meta_params"     = meta_params,
      "sessionInfo"     = sessionInfo()
    )
    
    
    # If the results were saved, tack the file names that the saves are under 
    # onto the end of metadata.
    if (save_results == TRUE) {
      # Generate the filepaths data was saved under. 
      # RD stands for Resource Dilution.
      metadata[["box_plot_png_name"]] <-
        auto_file_Name(
          prefix = "Boxplot_RD_",
          suffix = ".png",
          
          preserve_topology  = preserve_topology,
          testdata_type      = testdata_type,
          feature_type       = feature_type,
          number_ranks       = number_ranks,
          time_of_run        = time_of_run,
          trial_run          = trial_run)
      
      metadata[["line_plot_png_name"]] <-
        auto_file_Name(
          prefix = "Lineplot_RD_",
          suffix = ".png",
          
          preserve_topology  = preserve_topology,
          testdata_type      = testdata_type,
          feature_type       = feature_type,
          number_ranks       = number_ranks,
          time_of_run        = time_of_run,
          trial_run          = trial_run)
      
      metadata[["iterator_results_save_path"]] <-
        auto_file_Name(
          prefix = "Outputs/Resource_Dilution/Iterator_Results_RD_",
          suffix = ".RData",
          
          preserve_topology  = preserve_topology,
          testdata_type      = testdata_type,
          feature_type       = feature_type,
          number_ranks       = number_ranks,
          time_of_run        = time_of_run,
          trial_run          = trial_run)
    }
    
    
    # If the resource_Robustness() output was sunk and logged, append the 
    # file name of the log to the metadata.
    if (sink_output == TRUE) {
      # The file name includes many script_params in it to be informative and
      # unique. RD stands for Resource Dilution.
      metadata[["sink_logfile"]] <-
        auto_file_Name(
          prefix = "Outputs/Resource_Dilution/Logs/Complete_Log_RD_",
          suffix =  ".txt",
          
          preserve_topology  = preserve_topology,
          testdata_type      = testdata_type,
          feature_type       = feature_type,
          number_ranks       = number_ranks,
          time_of_run        = time_of_run,
          trial_run          = trial_run)
      
      
    }
    
    # If a warnings log was created for resource_Robustness(), append the file
    # name of the log to the metadata.
    if (liana_warnings == "divert") {
      # The file name includes many script_params in it to be informative and
      # unique. RD stands for Resource Dilution.
      metadata[["warning_logfile"]] <-
        auto_file_Name(
          prefix = "Outputs/Resource_Dilution/Logs/LIANA_warnings_RD_",
          suffix =  ".txt",
          
          preserve_topology  = preserve_topology,
          testdata_type      = testdata_type,
          feature_type       = feature_type,
          number_ranks       = number_ranks,
          time_of_run        = time_of_run,
          trial_run          = trial_run)
      
      
    }
    
    
    
    
    
    # return the metadata.
    return(metadata)
    
  } # end of function
  
  
  
}

# save_Results()
{
  #' 
  #'
  #'
  #'
  #'
  #'
  
  save_Results <- function(plot_box,
                           plot_line,
                           iterator_results,
                           
                           trial_run,
                           preserve_topology,
                           testdata_type,
                           feature_type,
                           number_ranks,
                           time_of_run) {
    
    # Generate the filepaths to save the data under. 
    # RD stands for Resource Dilution.
    box_plot_png_name <-
      auto_file_Name(
        prefix = "Boxplot_RD_",
        suffix = ".png",
        
        preserve_topology  = preserve_topology,
        testdata_type      = testdata_type,
        feature_type       = feature_type,
        number_ranks       = number_ranks,
        time_of_run        = time_of_run,
        trial_run          = trial_run)
    
    line_plot_png_name <-
      auto_file_Name(
        prefix = "Lineplot_RD_",
        suffix = ".png",
        
        preserve_topology  = preserve_topology,
        testdata_type      = testdata_type,
        feature_type       = feature_type,
        number_ranks       = number_ranks,
        time_of_run        = time_of_run,
        trial_run          = trial_run)
    
    iterator_results_save_path <- 
      auto_file_Name(
      prefix = "Outputs/Resource_Dilution/Iterator_Results_RD_",
      suffix = ".RData",
      
      preserve_topology  = preserve_topology,
      testdata_type      = testdata_type,
      feature_type       = feature_type,
      number_ranks       = number_ranks,
      time_of_run        = time_of_run,
      trial_run          = trial_run)
    
    
    
    
    # Save both plots
    ggsave(
      plot = plot_box,
      box_plot_png_name,
      height = 7.75,
      width = 8.00,
      path = "Outputs/Resource_Dilution"
    )
    
    ggsave(
      plot = plot_line,
      line_plot_png_name,
      height = 9.00,
      width = 8.00,
      path = "Outputs/Resource_Dilution"
    )
    
    # Save R environment and all the results within it
    save(iterator_results, file = iterator_results_save_path)
    
    
    
    
    # Let the user know where everything was stored.
    cat(str_wrap(str_glue("Box Plot saved at ~/Outputs/Resource_Dilution/",
                   box_plot_png_name, "."), width = 60), "\n\n")
    
    cat(str_wrap(str_glue("Line Plot saved at ~/Outputs/Resource_Dilution/",
                   line_plot_png_name, "."), width = 60), "\n\n")
    
    cat(str_wrap(str_glue("Iterator Results saved at ~/",
                   iterator_results_save_path, "."), width = 60), "\n\n")
    
  }  # end of function
}

# auto_file_Name()
{
  #' Automatically generates a file name or file path
  #' 
  #' @param prefix As a char. What should the file name start with? It could be
  #' a folder to make it a file path, such as "Outputs/", or any other tag, or 
  #' "".
  #' 
  #' @param suffix As a char. What should the file name end with? It should be a 
  #' file extension such as ".txt" or ".RData" at minimum, but it could also be
  #' more, such as "report.txt".
  #' 
  #' @param time_of_run What time was this script run at? Used to tag file names
  #' with a unique descriptor that allows the user to associate all the saved 
  #' files of the iterator together (the logs at 9:32 refer to the plot at 9:32 
  #' and the environment saved at 9:32). It also ensures that files from the 
  #' next time you run the iterator never overwrite old ones. Should always be 
  #' passed the time_of_run char generated by create_Params().
  #' 
  #' @param dilution_params What arguments were used in dilution robustness?
  #' This function will add the most relevant dilution parameters to the file 
  #' name. Should always be passed formals(wrap_resource_Robustness()).
  #' 
  #' @param meta_params What meta_data parameters were specified for the 
  #' iterator? If this was specified as a trial run of the iterator, file names
  #' are tagged with "TRIAL_RUN". Should always be passed 
  #' formals(summarise_Metadata).
  #' 
  #' @param testdata_type What type of testdata was used in the iterator? This
  #' function adds the testdadta type into the file name. Should always be 
  #' passed formals(extract_Testdata)$testdata_type.
  #' 
  #' @return A file name that starts with the prefix, ends with the suffix and 
  #' contains a bunch of parameter tags in between. This way the user can 
  #' identify the save file by the parameters it was set up with.
  
  
  auto_file_Name <- function(prefix,
                             suffix,
                             
                             trial_run,
                             preserve_topology,
                             testdata_type,
                             feature_type,
                             number_ranks,
                             time_of_run) {
    
    # We define individual comments related to relevant parameters and then 
    # string them all together for the save file name.
    
    # If this is a trial run, mark the save files as such
    if (trial_run == FALSE) {
      
      test_run_comment <- ""
      
    } else if (trial_run == TRUE) {
      
      test_run_comment <- "TRIAL_RUN_"
      
    }
    
    
    # How was the topology of diluted resources handled? Make an appropiate 
    # comment.
    if (preserve_topology == FALSE) {
      topology_comment <- "rand_topo_"
      
    } else if (preserve_topology == TRUE) {
      topology_comment <- "pres_topo_"
      
    }
    
    
    # ´What testdata_type was extracted and used with resource_Robustness?
    testdata_comment <-
      str_glue(testdata_type, "_")
    
    
    # What feature_type was dilution specified to occur with?
    feature_type_comment <-
      str_glue(feature_type, "_")
    
    
    # Make a comment out of the median top_n that was considered top_ranked. 
    # As a note, it could be a different number per method, but often it will
    # be the same number for every method.
    top_ranks_comment <-
      str_glue("top", median(unlist(number_ranks)), "_", )
    
    
    # Mash all the comments together with the suffix and prefix to create our
    # custom and hopefully informative file names
    auto_file_name <-
      str_glue(
        prefix,
        test_run_comment,
        testdata_comment,
        topology_comment,
        feature_type_comment,
        top_ranks_comment,
        time_of_run,
        suffix
      )
    
    return(auto_file_name)
  }  # end of function
  
}

